spring:
  application:
    name: llm-knowledge # 应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 使用阿里巴巴Druid数据库连接池
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://47.113.204.84:3306/lingyanlinghang?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true # 数据库连接URL
    username: root # 数据库用户名
    password: 2005M02y02c # 数据库密码
    druid:
      initial-size: 5 # 初始连接数
      min-idle: 5 # 最小连接数
      max-active: 20 # 最大连接数
      max-wait: 60000 # 获取连接等待超时时间
      time-between-eviction-runs-millis: 60000 # 间隔多久进行一次检测，检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 300000 # 一个连接在池中最小生存的时间
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true # 打开PSCache
      max-pool-prepared-statement-per-connection-size: 20 # 指定每个连接上PSCache的大小
  ai:
    openai:
      chat:
        enabled: true
        base-url: https://openai.maosuyu.com
        options:
          model: gpt-4o
      api-key:
  web:
    resources:
      static-locations: file:/D:/Desktop/llm-vue/src/assets/img/, classpath:/static/
  mvc:
    static-path-pattern: /images/upload/**    # 配置映射的 URL 路径前缀

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl       # 显示sql日志
  #    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl  # 不显示SQL
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  mapper-locations: classpath:mappers/*.xml


server:
  port: 10086


sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 3600
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 1800
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true


pagehelper:
  helper-dialect: mysql       # 数据库方言
  reasonable: true            # 启用合理化
  support-methods-arguments: true # 支持通过 Mapper 接口参数来传递分页参数
  params: count=countSql      # 配置 count 查询的方式

dify:
  apiKey: ${DIFY_APIKEY}
  apiHost: 'http://localhost/v1'


  hbase:
    zookeeper:
      quorum: master,slave1,slave2  # ZK集群节点
      port: 2181
    master: master:16000           # HBase Master地址
    rootdir: hdfs://master:9000/hbase  # HDFS存储路径

  hadoop:
    core-site:
      fs.defaultFS: hdfs://master:9000  # Hadoop核心配置