spring:
  application:
    name: llm-knowledge # 应用名称

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://47.113.204.84:3306/lingyanlinghang?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true # 数据库连接URL
    username: root # 数据库用户名
    password: 2005M02y02c # 数据库密码

mybatis-plus:
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl       # 显示sql日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl  # 不显示SQL
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑删除值
      logic-not-delete-value: 0 # 逻辑未删除值

server:
  port: 10086


